// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginwithvalidcredslogoutTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginwithvalidcredslogout() {
    driver.Navigate().GoToUrl("http://127.0.0.1:8777/");
    driver.Manage().Window.Size = new System.Drawing.Size(1022, 697);
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("admin@userqa.com");
    driver.FindElement(By.CssSelector(".form-fields")).Click();
    driver.FindElement(By.Id("Password")).Click();
    driver.FindElement(By.CssSelector(".login-button")).Click();
    driver.FindElement(By.LinkText("Log out")).Click();
  }
}
